### PR TITLE
Elastic Skin Support

### PR DESCRIPTION
**Pull request by texxasrulez**
This is working beautifully for me in Elastic Skin. Settings Icon is Font Awesome done ...

### CODE REVIEW

**Comment by maxxie85** [comment]
Activated this plugin fork, works like charm on RC 1.4.3.
Not using the internal dkim resolver.

**Comment by pimlie** [comment]
@texxasrulez Sorry for the delayed response and thanks for working on this.

Please have a look at composer.json, you might understand why I wont be able to merge this atm ;)

**Comment by texxasrulez** [comment]
No Prob on delay. We all get busy. I assumed you may not be here anymore, but reverted composer back to yours ... Thanks and have a great day

**Comment by pimlie** [comment]
@texxasrulez Thanks so much!

**Comment by tomsommer** [comment]
Awesome!

**Pull request merged**
